---
# tasks file for add_aws_sg
- name: Create security group {{ ec2_name_prefix }}-sg
  ec2_group:
    name: "{{ ec2_name_prefix }}-sg"
    description: "{{ ec2_name_prefix }}-sg"
    vpc_id: "{{ create_vpc.vpc.id }}"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: ec2_vpc_id is undefined
  register: create_sg
  until: create_sg is not failed
  retries: 5